### ISSUE TITLE
Cannot change the cluster storage setting after creating it.

### ISSUE THREAD

**Issue by Yoshiki0705** [aws/aws-parallelcluster-ui#113] opened 2023-03-11 10:12 UTC
## Description
I cannot change the cluster setting after creating it.

## Steps to reproduce the issue
(1)Select the cluster that you want to edit
(2)Click "Edit"
(3)Click "Next" in Step 2 Cluster.
(4)Click "Next" in Step 3 Head node
(5)Got the following message
Something went wrong
The application has encountered an unknown error and it is now in an inconsistent state. If you think that this is an error on our side, please help us improve by sending an error report on our GitHub issues page . Close this dialog to go back to the home page.
The error message: https://twitter.com/antiberial/status/1634496573785927680/photo/1
(5)Even delete the cluster and create new one, I could not edit the one as well

## Expected behaviour
Proceed to Step 4 Storage and change the storage setting for mounting points, storage services and so on.

## Actual behaviour
Please refer the above "Steps to reproduce the issue"

## Required info
- Region where ParallelCluster UI is installed: Tokyo(ap-northeast-1)
- Version of ParallelCluster UI and ParallelCluster: ParallelCluster: Manager 3.3.0 and ParallelCluster 3.5.0

## Additional info
The following information is not required but helpful:
 - OS: MacOS and Windows
 - Browser: chrome

**Comment by mtfranchetto** [comment] 2023-03-11 11:03
Hi @Yoshiki0705, thanks for the bug report! From what I see, I think the problem is the same as https://github.com/aws/aws-parallelcluster-ui/issues/69. It's been already mitigated but not released. Please look at the issue to see the mitigation.
Let me know if it works.

**Comment by Yoshiki0705** [comment] 2023-03-11 11:24
Hi @mtfranchetto, thanks for your quick reaction. Let me do it and reply to you. The environment is handled by my colleague and I may confirm it in Next Week.
By the way, can we keep this issue till the fixed version release? It's better to open the issues till it's solved and save people like me to take the mitigation smoothly.

**Comment by mtfranchetto** [comment] 2023-03-17 14:34
Hi @Yoshiki0705, have you been able to fix the issue?

**Comment by Yoshiki0705** [comment] 2023-03-18 14:25
Hi @mtfranchetto, I could mitigate the bug. So, we're waiting for the release the new version included the fix to close this issue.

**Comment by mtfranchetto** [comment] 2023-04-17 15:32
Hi @Yoshiki0705, we included this bugfix in the latest release of PCUI. Check the [Releases](https://github.com/aws/aws-parallelcluster-ui/releases) page for more info on what's included.
Closing the issue.

**Closed by mtfranchetto** 2023-04-17 15:32 UTC
Labels: bug-fixed-pending-release
